### ISSUE TITLE
Does this theme work with WooCommerce?

### ISSUE THREAD

**Issue by ethan-tqa** [imranhsayed/gatsby-wordpress-themes#16]
Hi there, my question is as the title, does this theme work with WooCommerce?

**Comment by imranhsayed** [comment]
Hi @ethan-tqa ,
Thank you for your query.
This theme is only for default posts and categories.
If you like you can create a woocommerce theme with Gatsby as well.
I will make a theme in Gatsby with woocommerce in future, however if you would like to build on your own, you can take a reference from the one I built using next.js, and implement it in Gatsby 
https://github.com/imranhsayed/woo-next

**Comment by ethan-tqa** [comment]
Great, thank you for the reply.
