### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by bnbabu55** [imranhsayed/gatsby-wordpress-themes#17]
I am getting this error when activating headless-cms plugin, can you please take look at it?
My set up, Wordpress 5.4.2, PHP 7.4.7 running locally using Laragon.

Plugin could not be activated because it triggered a fatal error.

Fatal error: Uncaught Error: Class 'Headless_CMS\Features\Inc\Plugin' not found in C:\Utilities\laragon\www\smrwp\wp-content\plugins\headless-cms\headless-cms.php:33 Stack trace: #0 C:\Utilities\laragon\www\smrwp\wp-content\plugins\headless-cms\headless-cms.php(36): headless_cms_features_plugin_loader() #1 C:\Utilities\laragon\www\smrwp\wp-admin\includes\plugin.php(2255): include('C:\\Utilities\\la...') #2 C:\Utilities\laragon\www\smrwp\wp-admin\plugins.php(177): plugin_sandbox_scrape('headless-cms/he...') #3 {main} thrown in C:\Utilities\laragon\www\smrwp\wp-content\plugins\headless-cms\headless-cms.php on line 33

**Comment by imranhsayed** [comment]
I am not getting any issues. Not sure why you are getting that. You may to debug!

![image](https://user-images.githubusercontent.com/11497423/86771707-55687280-c070-11ea-8d72-379ca1235441.png)
![image](https://user-images.githubusercontent.com/11497423/86771721-5c8f8080-c070-11ea-8bbe-00d7ff1d64dd.png)

**Comment by RangerCoder99** [comment]
Just because you are not getting this issue doesn't mean we are not getting it.,.. 
Maybe it got something to do with being on Windows?

**Comment by bnbabu55** [comment]
Just updated to version 1.0.3 and I am able to activate it now.

Thanks for the fix.
