### ISSUE TITLE
build fails on style.scss

### ISSUE THREAD

**Issue by witcradg** [imranhsayed/gatsby-wordpress-themes#20]
Generating development JavaScript bundle failed
		border: 1px solid $gray-200;
                   ^
      Undefined variable: "$gray-200".
      in /home/dean/projects/tutorials/phoenix/node_modules/@wordpress/block-library/src/calendar/style.scss (line 7, column 21)

File: node_modules/gatsby-wordpress-theme-phoenix/src/components/header/style.scss

**Comment by witcradg** [comment]
Trying to follow the instructions in the video. I created my site with Gatsby new... installed the plugin. Set up the gatsby-config.js to point at my WP (All plugins are installed). Tried to "gatsby develop" and got this error.
I'm probably doing something wrong but I haven't a clue. (I do have a lot of experience.)

**Comment by imranhsayed** [comment]
Thanks for sharing @witcradg 
can you please share your github repo. I will take a look

**Comment by witcradg** [comment]
I assume you'll want it to point at a WordPress site so I'll need to set that up since I'm working with a local install using localwp. If you just want the code, that's easier, I don't usually create github repos for tutorials so I'll need to do that.

**Comment by witcradg** [comment]
I did this a few times yesterday and started tinkering with what I had so I deleted the project and recreated it using the steps presented in https://www.youtube.com/watch?time_continue=24&v=73VAwNRwIag&feature=emb_logo
so we'd have a clean install.

gatsby new my-gatsby-project

replace gatsby-config.js content with

module.exports = {
    plugins: [
        // Tell gatsby which theme you will be using.
        {
        resolve: "gatsby-wordpress-theme-phoenix",
        options: {
            wordPressUrl: 'http://startersonly.local'
        }
    } ]
};

remove my-gatsby-project/src

npm i gatsby-wordpress-theme-phoenix

---
WordPress
I had previously installed the wp-graphiql and wp-graphiql plugins so I added headless-cms
advanced-custom-fields and wp-graphql-acf plugins.

I installed these from the respective repositories rather than using your zip files.
question: why is the advanced-custom-fields zip file named with the extra "ddd" (advanced-custom-fieldsddd.zip)?

Added Header and Footer Menus
Added 3 Pages and a couple Posts
imported the acf-data from your repo (acf.json) 
added the images and icons
selected the posts
---

in my-gatsby-project:
npm run develop

error as shown in the first message.
...next I'll create the repo.

**Comment by witcradg** [comment]
https://github.com/witcradg/my-gatsby-project

**Comment by imranhsayed** [comment]
Thanks for sharing @witcradg 
I don't see all the required files here https://github.com/witcradg/my-gatsby-project
I suggest to follow the readme of this repo.
If you want quick solution, you can also fork my repo and make changes as per your needs.

**Comment by miguelangeltorresfp** [comment]
I had the same problem working with the original project from @imranhsayed ( this repo ) and also with my project built following the youtube tutorial.
I found the solution from [Ganesh Dahal](https://css-tricks.com/creating-a-gatsby-site-with-wordpress-data/) and [Jason Lengstorf](https://egghead.io/lessons/gatsby-add-styles-for-wordpress-content-blocks-in-gatsby-pages)

`@import '~@wordpress/block-library/build-style/style.css';`

**Comment by imranhsayed** [comment]
@miguelangeltorresfp Thanks for writing.
Since the node_modules ( packages ) live outside the theme directory, making an alias for them.
So Gutenberg styles can be accessed like so `@import "~@wordpress/base-styles/colors"`

exports.onCreateWebpackConfig = ({ stage, actions }) => {
	actions.setWebpackConfig({
		resolve: {
			alias: {
				'~': path.resolve(__dirname, '../../node_modules')
			}
		},
	})
};

You can check it [here](https://github.com/imranhsayed/gatsby-wordpress-themes/blob/632b8379a470c6e702e2fe5b6c2937e57be26047/packages/gatsby-wordpress-theme-phoenix/gatsby-node.js#L17)

**Comment by imranhsayed** [comment]
I am assuming this is resolved. We can reopen if we still need help.

**Comment by alexam106** [comment]
> @miguelangeltorresfp Thanks for writing.
> You can check it [here](https://github.com/imranhsayed/gatsby-wordpress-themes/blob/632b8379a470c6e702e2fe5b6c2937e57be26047/packages/gatsby-wordpress-theme-phoenix/gatsby-node.js#L17)
> Since the node_modules ( packages ) live outside the theme directory, you can make an alias for them in `gatsby-node.js`
> So Gutenberg styles can be accessed like so `@import "~@wordpress/base-styles/colors"`
> 
> `exports.onCreateWebpackConfig = ({ stage, actions }) => { actions.setWebpackConfig({ resolve: { alias: { '~': path.resolve(__dirname, '../../node_modules') } }, }) };`

I try this and didn't work. Getting the same ERROR #98123  WEBPACK with the undefined color variables.

**Comment by KtaVC11** [comment]
> I had the same problem working with the original project from @imranhsayed ( this repo ) and also with my project built following the youtube tutorial.
> I found the solution from [Ganesh Dahal](https://css-tricks.com/creating-a-gatsby-site-with-wordpress-data/) and [Jason Lengstorf](https://egghead.io/lessons/gatsby-add-styles-for-wordpress-content-blocks-in-gatsby-pages)
> 
> I changed this line in the file: `_gutenberg-default.scss`
> 
> `@import '~@wordpress/block-library/build-style/style.css';`

Where Do I find that file?

**Comment by alexam106** [comment]
> @miguelangeltorresfp Thanks for writing.
> You can check it [here](https://github.com/imranhsayed/gatsby-wordpress-themes/blob/632b8379a470c6e702e2fe5b6c2937e57be26047/packages/gatsby-wordpress-theme-phoenix/gatsby-node.js#L17)
> Since the node_modules ( packages ) live outside the theme directory, you can make an alias for them in `gatsby-node.js`
> So Gutenberg styles can be accessed like so `@import "~@wordpress/base-styles/colors"`
> 
> `exports.onCreateWebpackConfig = ({ stage, actions }) => { actions.setWebpackConfig({ resolve: { alias: { '~': path.resolve(__dirname, '../../node_modules') } }, }) };`

where do i need to import this `@import "~@wordpress/base-styles/colors"` ? in the same `gatsby-node.js` file?

**Comment by KeviinCosmos** [comment]
A short video guide on this would be great :)

**Comment by beanymanuk** [comment]
I'm still looking for the solution to this if anyone has clear instructions. Thankyou
