### ISSUE TITLE
Style error on build

### ISSUE THREAD

**Issue by beanymanuk** [imranhsayed/gatsby-wordpress-themes#24]
Running npm run develop and getting this error any idea's where I've gone wrong

ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

                border: 1px solid $gray-300;
                   ^
      Undefined variable: "$gray-300".
      in C:\VS\my-gatsby-project\node_modules\@wordpress\block-library\src\calendar\style.scss (line 7, column 21)

File: node_modules\gatsby-wordpress-theme-phoenix\src\components\home\feature-posts\style.scss

**Comment by VivekShingala** [comment]
You can define one in this file and try build again.

`packages/gatsby-wordpress-theme-phoenix/src/sass/0-settings/_colors.scss`

Color code for gray 300 could be `.text-gray-300 | color: #e2e8f0;` taken from tailwind [Text Color](https://tailwindcss.com/docs/text-color)

**Comment by beanymanuk** [comment]
Thankyou I overcome that issue and project now builds

I now get this error which I guess it's not detecting my site? 
https://cms.peter-gosling.com/

I have added it in here
module.exports = {
  plugins: [
      // Tell gatsby which theme you will be using.
      {
      resolve: "gatsby-wordpress-theme-phoenix",
      options: {
          wordPressUrl: 'https://cms.peter-gosling.com'
      }
  } ]
};

TypeError: Cannot read property 'frontPageMeta' of null
FrontPage
C:/VS/my-gatsby-project/node_modules/gatsby-wordpress-theme-phoenix/src/templates/front-page/index.js:10
   7 | import Error from "../../components/error";
   8 | import { isEmpty } from 'lodash';
   9 | 
> 10 | const FrontPage = ( props ) => {
  11 | 
  12 | 	const {
  13 | 		      pageContext: {

**Comment by imranhsayed** [comment]
Tried a fresh clone
yarn install in the root
then npm run dev
I am unable to replicate this issue. Since its resolved now. Closing this one. If any anyone still faces this issue, it can be reponened.
