### ISSUE TITLE
Cannot read property 'HWGraphQL' of undefined

### ISSUE THREAD

**Issue by priscaure** [imranhsayed/gatsby-wordpress-themes#29]
Hi :) 

Had no problems 1 week earlier while running your theme, but since today I can't quite make it work.
It keeps crashing when creating the pages.

I have these 2 errors : 
`Cannot query field "content" on type "hwgraphql_Page".`
`gatsby-wordpress-theme-phoenix threw an error while running the createPages lifecycle`

And I didn't change anything... 

This theme is awesome by the way ! Can't wait to make my way through it !

Kind regards,
Prisca

**Comment by imranhsayed** [comment]
Did you update any plugins?
Please ensure you are using the same versions of the plugin from the wordpress/plugins directory of the repo.

**Comment by priscaure** [comment]
> Did you update any plugins?
> Please ensure you are using the same versions of the plugin from the wordpress/plugins directory of the repo.

Hello, 

You were absolutely right, i have the tendency of updating everything. That was the case, everything is back to normal now :) 

Thank you so much ! 😊

**Comment by mwoodpatrick** [comment]
I hit this problem also. Is there a long-term fix for this it does not seem reasonable to continue to use older versions of plugins when there is a newer version available? My error output is attached

[gatsby-wordpress-themes-error.log](https://github.com/imranhsayed/gatsby-wordpress-themes/files/6160412/gatsby-wordpress-themes-error.log)
